import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import GlobalLoader from "@/components/ui/GlobalLoader";
import {AuthProvider} from "@/context/AuthContext";
import Providers from "./providers"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
          <body suppressHydrationWarning>
              {/*<GlobalLoader />*/}
              <AuthProvider>
                  <Providers>
                      <Header />
                      {children}


                      <Footer />
                  </Providers>
              </AuthProvider>
          </body>
      </html>
  );
}
