import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import GlobalLoader from "@/components/ui/GlobalLoader";
import {AuthProvider} from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
      <AuthProvider>
          <Header />
          {children}
          <GlobalLoader />
          <Footer />
      </AuthProvider>
      </body>
      </html>
  );
}
