export const EnglishQuestions = [
  // ===== Level 0 =====
  {
    id: 1,
    level: "0",
    question: "____ is your name?",
    option1: "What",
    option2: "Where",
    option3: "Who",
    option4: "How",
    answer: "What",
  },
  {
    id: 2,
    level: "0",
    question: "Choose the opposite of 'big'.",
    option1: "small",
    option2: "huge",
    option3: "tall",
    option4: "large",
    answer: "small",
  },
  {
    id: 3,
    level: "0",
    question: "I ____ ten years old.",
    option1: "is",
    option2: "am",
    option3: "are",
    option4: "be",
    answer: "am",
  },
  {
    id: 4,
    level: "0",
    question: "She ____ my friend.",
    option1: "is",
    option2: "are",
    option3: "am",
    option4: "be",
    answer: "is",
  },
  {
    id: 5,
    level: "0",
    question: "Which one is a color?",
    option1: "dog",
    option2: "blue",
    option3: "run",
    option4: "milk",
    answer: "blue",
  },
  {
    id: 6,
    level: "0",
    question: "What is the plural of 'book'?",
    option1: "bookes",
    option2: "books",
    option3: "book",
    option4: "bookies",
    answer: "books",
  },
  {
    id: 7,
    level: "0",
    question: "They ____ students.",
    option1: "is",
    option2: "am",
    option3: "are",
    option4: "be",
    answer: "are",
  },
  {
    id: 8,
    level: "0",
    question: "I ____ from Spain.",
    option1: "is",
    option2: "am",
    option3: "are",
    option4: "be",
    answer: "am",
  },
  {
    id: 9,
    level: "0",
    question: "Which one is an animal?",
    option1: "Cat",
    option2: "Table",
    option3: "Water",
    option4: "Red",
    answer: "Cat",
  },
  {
    id: 10,
    level: "0",
    question: "Choose the opposite of 'hot'.",
    option1: "warm",
    option2: "cold",
    option3: "heat",
    option4: "cool",
    answer: "cold",
  },

  // ===== Level A =====
  {
    id: 11,
    level: "A",
    question: "Which word means the same as 'happy'?",
    option1: "sad",
    option2: "glad",
    option3: "angry",
    option4: "tired",
    answer: "glad",
  },
  {
    id: 12,
    level: "A",
    question: "Which one is a synonym for 'fast'?",
    option1: "slow",
    option2: "quick",
    option3: "lazy",
    option4: "late",
    answer: "quick",
  },
  {
    id: 13,
    level: "A",
    question: "He ____ football every weekend.",
    option1: "play",
    option2: "plays",
    option3: "playing",
    option4: "played",
    answer: "plays",
  },
  {
    id: 14,
    level: "A",
    question: "They ____ to school yesterday.",
    option1: "go",
    option2: "goes",
    option3: "went",
    option4: "gone",
    answer: "went",
  },
  {
    id: 15,
    level: "A",
    question: "Which is the opposite of 'early'?",
    option1: "late",
    option2: "fast",
    option3: "soon",
    option4: "quick",
    answer: "late",
  },
  {
    id: 16,
    level: "A",
    question: "Choose the correct sentence:",
    option1: "She don't like pizza.",
    option2: "She doesn't likes pizza.",
    option3: "She doesn't like pizza.",
    option4: "She not like pizza.",
    answer: "She doesn't like pizza.",
  },
  {
    id: 17,
    level: "A",
    question: "Which one is a job?",
    option1: "doctor",
    option2: "happy",
    option3: "sing",
    option4: "blue",
    answer: "doctor",
  },
  {
    id: 18,
    level: "A",
    question: "Choose the correct option: I ____ English now.",
    option1: "learn",
    option2: "am learning",
    option3: "learning",
    option4: "learned",
    answer: "am learning",
  },
  {
    id: 19,
    level: "A",
    question: "What is the opposite of 'cheap'?",
    option1: "expensive",
    option2: "low",
    option3: "small",
    option4: "costly",
    answer: "expensive",
  },
  {
    id: 20,
    level: "A",
    question: "She ____ coffee every morning.",
    option1: "drink",
    option2: "drinks",
    option3: "drank",
    option4: "drinking",
    answer: "drinks",
  },

  // ===== Level B =====
  {
    id: 21,
    level: "B",
    question: "Which is the closest synonym for 'alleviate'?",
    option1: "intensify",
    option2: "relieve",
    option3: "prevent",
    option4: "ignore",
    answer: "relieve",
  },
  {
    id: 22,
    level: "B",
    question:
      "Choose the correct relative clause: The book, ____ I borrowed last week, is fantastic.",
    option1: "that",
    option2: "which",
    option3: "whom",
    option4: "what",
    answer: "which",
  },
  {
    id: 23,
    level: "B",
    question: "If she ____ harder, she might have passed the exam.",
    option1: "has studied",
    option2: "had studied",
    option3: "studied",
    option4: "would study",
    answer: "had studied",
  },
  {
    id: 24,
    level: "B",
    question: "Which word is closest in meaning to 'meticulous'?",
    option1: "careless",
    option2: "precise",
    option3: "hasty",
    option4: "rough",
    answer: "precise",
  },
  {
    id: 25,
    level: "B",
    question: "He insisted that she ____ present at the meeting.",
    option1: "be",
    option2: "was",
    option3: "is",
    option4: "should be",
    answer: "be",
  },
  {
    id: 26,
    level: "B",
    question: "Which is the correct phrasal verb meaning 'give up'?",
    option1: "call off",
    option2: "give in",
    option3: "put off",
    option4: "take off",
    answer: "give in",
  },
  {
    id: 27,
    level: "B",
    question: "By the time we arrived, they ____ dinner.",
    option1: "had had",
    option2: "have had",
    option3: "were having",
    option4: "had been having",
    answer: "had had",
  },
  {
    id: 28,
    level: "B",
    question: "Which word is closest in meaning to 'elaborate'?",
    option1: "simple",
    option2: "detailed",
    option3: "quick",
    option4: "vague",
    answer: "detailed",
  },
  {
    id: 29,
    level: "B",
    question: "The synonym of 'enormous' is ____.",
    option1: "tiny",
    option2: "huge",
    option3: "small",
    option4: "little",
    answer: "huge",
  },
  {
    id: 30,
    level: "B",
    question: "Choose the correct passive form: The book ____ by many people.",
    option1: "is read",
    option2: "reads",
    option3: "read",
    option4: "reading",
    answer: "is read",
  },

  // ===== Level C =====
  {
    id: 31,
    level: "C",
    question: "Which word is closest in meaning to 'ubiquitous'?",
    option1: "rare",
    option2: "everywhere",
    option3: "hidden",
    option4: "absent",
    answer: "everywhere",
  },
  {
    id: 32,
    level: "C",
    question:
      "Choose the correct inversion: Rarely ____ such an opportunity again.",
    option1: "do we see",
    option2: "we see",
    option3: "we saw",
    option4: "have we see",
    answer: "do we see",
  },
  {
    id: 33,
    level: "C",
    question: "If he ____ me earlier, I would have warned him.",
    option1: "had told",
    option2: "told",
    option3: "would tell",
    option4: "has told",
    answer: "had told",
  },
  {
    id: 34,
    level: "C",
    question: "Not only did she win the prize ____ she also donated it.",
    option1: "but",
    option2: "and",
    option3: "but also",
    option4: "so",
    answer: "but also",
  },
  {
    id: 35,
    level: "C",
    question:
      "The manuscript, ____ deeply by critics, has yet to be published.",
    option1: "scrutinised",
    option2: "scrutinising",
    option3: "having scrutinised",
    option4: "to scrutinise",
    answer: "scrutinised",
  },
  {
    id: 36,
    level: "C",
    question: "Which word is closest in meaning to 'circumspect'?",
    option1: "rash",
    option2: "cautious",
    option3: "reckless",
    option4: "careless",
    answer: "cautious",
  },
  {
    id: 37,
    level: "C",
    question: "No sooner ____ the meeting than problems started.",
    option1: "had started",
    option2: "we had started",
    option3: "had we started",
    option4: "did we start",
    answer: "had we started",
  },
  {
    id: 38,
    level: "C",
    question: "I suggest that he ____ early tomorrow.",
    option1: "leaves",
    option2: "leave",
    option3: "will leave",
    option4: "left",
    answer: "leave",
  },
  {
    id: 39,
    level: "C",
    question: "The synonym of 'conspicuous' is ____.",
    option1: "noticeable",
    option2: "invisible",
    option3: "hidden",
    option4: "unknown",
    answer: "noticeable",
  },
  {
    id: 40,
    level: "C",
    question: "Rarely ____ seen such chaos.",
    option1: "I have",
    option2: "have I",
    option3: "I had",
    option4: "had I",
    answer: "have I",
  },
];
